// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTestsParams creates a new GetTestsParams object
// with the default values initialized.
func NewGetTestsParams() *GetTestsParams {
	var ()
	return &GetTestsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTestsParamsWithTimeout creates a new GetTestsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTestsParamsWithTimeout(timeout time.Duration) *GetTestsParams {
	var ()
	return &GetTestsParams{

		timeout: timeout,
	}
}

// NewGetTestsParamsWithContext creates a new GetTestsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTestsParamsWithContext(ctx context.Context) *GetTestsParams {
	var ()
	return &GetTestsParams{

		Context: ctx,
	}
}

// NewGetTestsParamsWithHTTPClient creates a new GetTestsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTestsParamsWithHTTPClient(client *http.Client) *GetTestsParams {
	var ()
	return &GetTestsParams{
		HTTPClient: client,
	}
}

/*GetTestsParams contains all the parameters to send to the API endpoint
for the get tests operation typically these are written to a http.Request
*/
type GetTestsParams struct {

	/*Fields*/
	Fields *string
	/*Locator*/
	Locator *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tests params
func (o *GetTestsParams) WithTimeout(timeout time.Duration) *GetTestsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tests params
func (o *GetTestsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tests params
func (o *GetTestsParams) WithContext(ctx context.Context) *GetTestsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tests params
func (o *GetTestsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tests params
func (o *GetTestsParams) WithHTTPClient(client *http.Client) *GetTestsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tests params
func (o *GetTestsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get tests params
func (o *GetTestsParams) WithFields(fields *string) *GetTestsParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get tests params
func (o *GetTestsParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithLocator adds the locator to the get tests params
func (o *GetTestsParams) WithLocator(locator *string) *GetTestsParams {
	o.SetLocator(locator)
	return o
}

// SetLocator adds the locator to the get tests params
func (o *GetTestsParams) SetLocator(locator *string) {
	o.Locator = locator
}

// WriteToRequest writes these params to a swagger request
func (o *GetTestsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.Locator != nil {

		// query param locator
		var qrLocator string
		if o.Locator != nil {
			qrLocator = *o.Locator
		}
		qLocator := qrLocator
		if qLocator != "" {
			if err := r.SetQueryParam("locator", qLocator); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
