// Code generated by go-swagger; DO NOT EDIT.

package test_occurrence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/cvbarros/go-teamcity-sdk/models"
)

// GetTestOccurrencesReader is a Reader for the GetTestOccurrences structure.
type GetTestOccurrencesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTestOccurrencesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTestOccurrencesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTestOccurrencesOK creates a GetTestOccurrencesOK with default headers values
func NewGetTestOccurrencesOK() *GetTestOccurrencesOK {
	return &GetTestOccurrencesOK{}
}

/*GetTestOccurrencesOK handles this case with default header values.

successful operation
*/
type GetTestOccurrencesOK struct {
	Payload *models.TestOccurrences
}

func (o *GetTestOccurrencesOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/testOccurrences][%d] getTestOccurrencesOK  %+v", 200, o.Payload)
}

func (o *GetTestOccurrencesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TestOccurrences)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
