// Code generated by go-swagger; DO NOT EDIT.

package test_occurrence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new test occurrence API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for test occurrence API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetTestOccurrences get test occurrences API
*/
func (a *Client) GetTestOccurrences(params *GetTestOccurrencesParams) (*GetTestOccurrencesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTestOccurrencesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getTestOccurrences",
		Method:             "GET",
		PathPattern:        "/app/rest/testOccurrences",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTestOccurrencesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTestOccurrencesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
