// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ProgressInfo progress info
// swagger:model ProgressInfo
type ProgressInfo struct {

	// done
	Done int64 `json:"done,omitempty"`

	// done humanized
	DoneHumanized string `json:"doneHumanized,omitempty"`

	// estimated
	Estimated int64 `json:"estimated,omitempty"`

	// estimated humanized
	EstimatedHumanized string `json:"estimatedHumanized,omitempty"`

	// percent
	Percent int32 `json:"percent,omitempty"`

	// phase
	Phase string `json:"phase,omitempty"`
}

// Validate validates this progress info
func (m *ProgressInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ProgressInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProgressInfo) UnmarshalBinary(b []byte) error {
	var res ProgressInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
