// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TestOccurrence test occurrence
// swagger:model testOccurrence
type TestOccurrence struct {

	// build
	Build *Build `json:"build,omitempty"`

	// currently investigated
	CurrentlyInvestigated *bool `json:"currentlyInvestigated,omitempty" xml:"currentlyInvestigated"`

	// currently muted
	CurrentlyMuted *bool `json:"currentlyMuted,omitempty" xml:"currentlyMuted"`

	// details
	Details string `json:"details,omitempty"`

	// duration
	Duration int32 `json:"duration,omitempty" xml:"duration"`

	// first failed
	FirstFailed *TestOccurrence `json:"firstFailed,omitempty"`

	// href
	Href string `json:"href,omitempty" xml:"href"`

	// id
	ID string `json:"id,omitempty" xml:"id"`

	// ignore details
	IgnoreDetails string `json:"ignoreDetails,omitempty"`

	// ignored
	Ignored *bool `json:"ignored,omitempty" xml:"ignored"`

	// invocations
	Invocations *TestOccurrences `json:"invocations,omitempty"`

	// mute
	Mute *Mute `json:"mute,omitempty"`

	// muted
	Muted *bool `json:"muted,omitempty" xml:"muted"`

	// name
	Name string `json:"name,omitempty" xml:"name"`

	// next fixed
	NextFixed *TestOccurrence `json:"nextFixed,omitempty"`

	// run order
	RunOrder string `json:"runOrder,omitempty" xml:"runOrder"`

	// status
	Status string `json:"status,omitempty" xml:"status"`

	// test
	Test *Test `json:"test,omitempty"`
}

// Validate validates this test occurrence
func (m *TestOccurrence) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuild(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateFirstFailed(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateInvocations(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateMute(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateNextFixed(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTest(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TestOccurrence) validateBuild(formats strfmt.Registry) error {

	if swag.IsZero(m.Build) { // not required
		return nil
	}

	if m.Build != nil {

		if err := m.Build.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("build")
			}
			return err
		}
	}

	return nil
}

func (m *TestOccurrence) validateFirstFailed(formats strfmt.Registry) error {

	if swag.IsZero(m.FirstFailed) { // not required
		return nil
	}

	if m.FirstFailed != nil {

		if err := m.FirstFailed.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("firstFailed")
			}
			return err
		}
	}

	return nil
}

func (m *TestOccurrence) validateInvocations(formats strfmt.Registry) error {

	if swag.IsZero(m.Invocations) { // not required
		return nil
	}

	if m.Invocations != nil {

		if err := m.Invocations.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("invocations")
			}
			return err
		}
	}

	return nil
}

func (m *TestOccurrence) validateMute(formats strfmt.Registry) error {

	if swag.IsZero(m.Mute) { // not required
		return nil
	}

	if m.Mute != nil {

		if err := m.Mute.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mute")
			}
			return err
		}
	}

	return nil
}

func (m *TestOccurrence) validateNextFixed(formats strfmt.Registry) error {

	if swag.IsZero(m.NextFixed) { // not required
		return nil
	}

	if m.NextFixed != nil {

		if err := m.NextFixed.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("nextFixed")
			}
			return err
		}
	}

	return nil
}

func (m *TestOccurrence) validateTest(formats strfmt.Registry) error {

	if swag.IsZero(m.Test) { // not required
		return nil
	}

	if m.Test != nil {

		if err := m.Test.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("test")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TestOccurrence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TestOccurrence) UnmarshalBinary(b []byte) error {
	var res TestOccurrence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
